name: cd

on: 
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Remove old container
        run: podman rm -f gassigeher
        continue-on-error: true
      - name: Build image
        run: podman build -t gassigeher:latest .
      - name: Create data directory
        run: New-Item -ItemType Directory -Force -Path data
      - name: Create uploads directory
        run: New-Item -ItemType Directory -Force -Path uploads
      - name: Run new container
        run: podman run -d --name gassigeher -p 8888:8888 -v ./data:/app/data:Z -v ./uploads:/app/uploads:Z -e DATABASE_PATH=/app/data/gassigeher.db gassigeher:latest